import type { Metadata } from "next";
import { Montserrat} from "next/font/google";
import "./globals.scss";

const MontserratFont = Montserrat({
    subsets: ['latin'],
    weight: ['200', '300', '400', '500', '600', '700', '800', ],
    preload: true,
    display: 'swap',
    fallback: ['system-ui', 'sans-serif'],
    variable: '--font-primary',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${MontserratFont.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
